services:
  - type: web
    name: student-leave-backend
    env: docker
    region: ohio
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    port: 8080
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: DATABASE_DRIVER
        value: org.postgresql.Driver
      - key: DATABASE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect

