# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlite:studentleave.db}
# If we are on Render, use Postgres driver, otherwise use SQLite
spring.datasource.driver-class-name=${JDBC_DRIVER:org.sqlite.JDBC}

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Force the dialect for PostgreSQL when on Render
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.community.dialect.SQLiteDialect}

# Compatibility for PostgreSQL on Render
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Server port
server.port=8080




